import 'package:flutter/material.dart';
import 'package:pandlive/App/Models/country_picker_model.dart';

class CountryService {
  static List<CountryModel> getCountries(BuildContext context) {
    final locale = Localizations.localeOf(context).languageCode;

    return _countries.entries.map((e) {
      return CountryModel(
        code: e.key,
        name: locale == "ar" ? e.value["ar"]! : e.value["en"]!,
      );
    }).toList();
  }

  static final Map<String, Map<String, String>> _countries = {
    "AF": {"en": "Afghanistan", "ar": "أفغانستان"},
    "AL": {"en": "Albania", "ar": "ألبانيا"},
    "DZ": {"en": "Algeria", "ar": "الجزائر"},
    "AD": {"en": "Andorra", "ar": "أندورا"},
    "AO": {"en": "Angola", "ar": "أنغولا"},
    "AR": {"en": "Argentina", "ar": "الأرجنتين"},
    "AM": {"en": "Armenia", "ar": "أرمينيا"},
    "AU": {"en": "Australia", "ar": "أستراليا"},
    "AT": {"en": "Austria", "ar": "النمسا"},
    "AZ": {"en": "Azerbaijan", "ar": "أذربيجان"},
    "BH": {"en": "Bahrain", "ar": "البحرين"},
    "BD": {"en": "Bangladesh", "ar": "بنغلاديش"},
    "BE": {"en": "Belgium", "ar": "بلجيكا"},
    "BR": {"en": "Brazil", "ar": "البرازيل"},
    "BG": {"en": "Bulgaria", "ar": "بلغاريا"},
    "CA": {"en": "Canada", "ar": "كندا"},
    "CN": {"en": "China", "ar": "الصين"},
    "CO": {"en": "Colombia", "ar": "كولومبيا"},
    "HR": {"en": "Croatia", "ar": "كرواتيا"},
    "CY": {"en": "Cyprus", "ar": "قبرص"},
    "CZ": {"en": "Czech Republic", "ar": "جمهورية التشيك"},
    "DK": {"en": "Denmark", "ar": "الدنمارك"},
    "EG": {"en": "Egypt", "ar": "مصر"},
    "FI": {"en": "Finland", "ar": "فنلندا"},
    "FR": {"en": "France", "ar": "فرنسا"},
    "DE": {"en": "Germany", "ar": "ألمانيا"},
    "GR": {"en": "Greece", "ar": "اليونان"},
    "HU": {"en": "Hungary", "ar": "المجر"},
    "IN": {"en": "India", "ar": "الهند"},
    "ID": {"en": "Indonesia", "ar": "إندونيسيا"},
    "IR": {"en": "Iran", "ar": "إيران"},
    "IQ": {"en": "Iraq", "ar": "العراق"},
    "IE": {"en": "Ireland", "ar": "إيرلندا"},
    "IL": {"en": "Israel", "ar": "إسرائيل"},
    "IT": {"en": "Italy", "ar": "إيطاليا"},
    "JP": {"en": "Japan", "ar": "اليابان"},
    "JO": {"en": "Jordan", "ar": "الأردن"},
    "KW": {"en": "Kuwait", "ar": "الكويت"},
    "LB": {"en": "Lebanon", "ar": "لبنان"},
    "LY": {"en": "Libya", "ar": "ليبيا"},
    "MY": {"en": "Malaysia", "ar": "ماليزيا"},
    "MX": {"en": "Mexico", "ar": "المكسيك"},
    "MA": {"en": "Morocco", "ar": "المغرب"},
    "NL": {"en": "Netherlands", "ar": "هولندا"},
    "NZ": {"en": "New Zealand", "ar": "نيوزيلندا"},
    "NG": {"en": "Nigeria", "ar": "نيجيريا"},
    "NO": {"en": "Norway", "ar": "النرويج"},
    "OM": {"en": "Oman", "ar": "عُمان"},
    "PK": {"en": "Pakistan", "ar": "باكستان"},
    "PH": {"en": "Philippines", "ar": "الفلبين"},
    "PL": {"en": "Poland", "ar": "بولندا"},
    "PT": {"en": "Portugal", "ar": "البرتغال"},
    "QA": {"en": "Qatar", "ar": "قطر"},
    "RO": {"en": "Romania", "ar": "رومانيا"},
    "RU": {"en": "Russia", "ar": "روسيا"},
    "SA": {"en": "Saudi Arabia", "ar": "المملكة العربية السعودية"},
    "SG": {"en": "Singapore", "ar": "سنغافورة"},
    "ZA": {"en": "South Africa", "ar": "جنوب أفريقيا"},
    "KR": {"en": "South Korea", "ar": "كوريا الجنوبية"},
    "ES": {"en": "Spain", "ar": "إسبانيا"},
    "SE": {"en": "Sweden", "ar": "السويد"},
    "CH": {"en": "Switzerland", "ar": "سويسرا"},
    "SY": {"en": "Syria", "ar": "سوريا"},
    "TH": {"en": "Thailand", "ar": "تايلاند"},
    "TR": {"en": "Turkey", "ar": "تركيا"},
    "AE": {"en": "United Arab Emirates", "ar": "الإمارات العربية المتحدة"},
    "GB": {"en": "United Kingdom", "ar": "المملكة المتحدة"},
    "US": {"en": "United States", "ar": "الولايات المتحدة"},
    "VN": {"en": "Vietnam", "ar": "فيتنام"},
    "YE": {"en": "Yemen", "ar": "اليمن"},
    "ZW": {"en": "Zimbabwe", "ar": "زيمبابوي"},
  };
}
